#
# This file is part of BDC-Catalog.
# Copyright (C) 2019-2020 INPE.
#
# BDC-Catalog is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.
#

kind: pipeline
name: default

steps:
- name: test
  image: python:3.7
  environment:
    SQLALCHEMY_DATABASE_URI: postgresql://postgres:mysecretpassword@postgis:5432/bdc_db
  commands:
  - pip install --upgrade pip
  - pip install --upgrade setuptools
  - pip install -e .[tests,docs]
  - ./run-tests.sh


- name: coverage
  image: plugins/codecov
  when:
    event:
      - push
  settings:
    token:
      from_secret: codecov_token
    files:
      - coverage.xml
      - .coverage


services:
- name: postgis
  image: postgis/postgis:12-3.1
  environment:
    POSTGRES_PASSWORD: mysecretpassword
    POSTGRES_USER: postgres
