"""0.4.1

Revision ID: 02d16d3da520
Revises: 432e3447c36b
Create Date: 2020-08-28 11:03:08.595424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02d16d3da520'
down_revision = '432e3447c36b'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('quicklook_collection_id_collections_fkey', 'quicklook', type_='foreignkey', schema='bdc')
    op.create_foreign_key(op.f('quicklook_collection_id_collections_fkey'), 'quicklook', 'collections', ['collection_id'], ['id'], source_schema='bdc', referent_schema='bdc', onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ##
    op.drop_constraint(op.f('quicklook_collection_id_collections_fkey'), 'quicklook', schema='bdc', type_='foreignkey')
    op.create_foreign_key('quicklook_collection_id_collections_fkey', 'quicklook', 'collections', ['collection_id'], ['id'], source_schema='bdc', referent_schema='bdc')
    # ### end Alembic commands ###
