"""add item access control

Revision ID: 38d006c95099
Revises: c68b17b1860b
Create Date: 2021-01-26 13:46:34.976341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38d006c95099'
down_revision = 'c68b17b1860b'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('is_public', sa.Boolean(), nullable=False), schema='bdc')
    op.create_index(op.f('idx_bdc_items_is_public'), 'items', ['is_public'], unique=False, schema='bdc')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_bdc_items_is_public'), table_name='items', schema='bdc')
    op.drop_column('items', 'is_public', schema='bdc')
    # ### end Alembic commands ###
