"""add minimal roles system

Revision ID: 5067fb4381c0
Revises: d01f09b5dd8b
Create Date: 2022-08-15 09:01:16.510820

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5067fb4381c0'
down_revision = 'd01f09b5dd8b'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'is_public', schema='bdc')

    op.create_table(
        'roles',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('name', sa.String(length=64), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('created', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id', name=op.f('roles_pkey')),
        sa.UniqueConstraint('name', name=op.f('roles_name_key')),
        schema='bdc'
    )
    op.create_index(op.f('idx_bdc_roles_name'), 'roles', ['name'], unique=False, schema='bdc')
    op.create_table(
        'collections_roles',
        sa.Column('collection_id', sa.Integer(), nullable=False),
        sa.Column('role_id', sa.Integer(), nullable=False),
        sa.Column('created', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['collection_id'], ['bdc.collections.id'], name=op.f('collections_roles_collection_id_collections_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['role_id'], ['bdc.roles.id'], name=op.f('collections_roles_role_id_roles_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('collection_id', 'role_id', name=op.f('collections_roles_pkey')),
        schema='bdc'
    )

    op.create_index(op.f('idx_bdc_quicklook_collection_id'), 'quicklook', ['collection_id'], unique=False, schema='bdc')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_bdc_quicklook_collection_id'), table_name='quicklook', schema='bdc')

    op.drop_table('collections_roles', schema='bdc')
    op.drop_index(op.f('idx_bdc_roles_name'), table_name='roles', schema='bdc')
    op.drop_table('roles', schema='bdc')

    op.add_column('items', sa.Column('is_public', sa.Boolean, nullable=True, default=True, server_default='true'),
                  schema='bdc')
    # ### end Alembic commands ###
