"""fix optional jsonb columns

Revision ID: 98ba50e6e9ab
Revises: f3112636be24
Create Date: 2023-05-12 09:00:13.859502

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '98ba50e6e9ab'
down_revision = 'f3112636be24'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('collections', 'properties',
                    existing_type=postgresql.JSONB(astext_type=sa.Text()),
                    nullable=True,
                    server_default='{}',
                    comment='Contains the properties offered by STAC collections',
                    schema='bdc')

    op.alter_column('collections', 'summaries',
                    existing_type=postgresql.JSONB(astext_type=sa.Text()),
                    nullable=True,
                    server_default='{}',
                    comment='Contains the STAC Collection summaries.',
                    schema='bdc')

    op.alter_column('collections', 'item_assets',
                    existing_type=postgresql.JSONB(astext_type=sa.Text()),
                    nullable=True,
                    server_default='{}',
                    comment='Contains the STAC Extension Item Assets.',
                    schema='bdc')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('collections', 'properties',
                    existing_type=postgresql.JSONB(astext_type=sa.Text()),
                    nullable=True,
                    comment='Contains the properties offered by STAC collections',
                    schema='bdc')

    op.alter_column('collections', 'summaries',
                    existing_type=postgresql.JSONB(astext_type=sa.Text()),
                    nullable=True,
                    comment='Contains the STAC Collection summaries.',
                    schema='bdc')

    op.alter_column('collections', 'item_assets',
                    existing_type=postgresql.JSONB(astext_type=sa.Text()),
                    nullable=True,
                    comment='Contains the STAC Extension Item Assets.',
                    schema='bdc')

    # ### end Alembic commands ###
