"""v0.6.0

Revision ID: be5ae740887a
Revises: f3f27ad116d2
Create Date: 2020-09-01 09:46:24.489341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be5ae740887a'
down_revision = 'f3f27ad116d2'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('band_src',
    sa.Column('band_id', sa.Integer(), nullable=False),
    sa.Column('band_src_id', sa.Integer(), nullable=False),
    sa.Column('created', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['band_id'], ['bdc.bands.id'], name=op.f('band_src_band_id_bands_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['band_src_id'], ['bdc.bands.id'], name=op.f('band_src_band_src_id_bands_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('band_id', 'band_src_id', name=op.f('band_src_pkey')),
    schema='bdc'
    )
    op.alter_column('collections', 'version',
               existing_type=sa.VARCHAR(length=3),
               type_=sa.Integer(),
               existing_nullable=False,
               schema='bdc',
               postgresql_using='version::integer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('collections', 'version',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=3),
               existing_nullable=False,
               schema='bdc')
    op.drop_table('band_src', schema='bdc')
    # ### end Alembic commands ###
