"""timeline

Revision ID: f3f27ad116d2
Revises: 149deb59082a
Create Date: 2020-08-28 19:37:51.589163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3f27ad116d2'
down_revision = '149deb59082a'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timeline',
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.Column('time_inst', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['bdc.collections.id'], name=op.f('timeline_collection_id_collections_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('collection_id', 'time_inst', name=op.f('timeline_pkey')),
    schema='bdc'
    )
    op.create_index(op.f('idx_bdc_timeline_collection_id'), 'timeline', ['collection_id', sa.text('time_inst DESC')], unique=False, schema='bdc')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_bdc_timeline_collection_id'), table_name='timeline', schema='bdc')
    op.drop_table('timeline', schema='bdc')
    # ### end Alembic commands ###
