"""empty message

Revision ID: 0b986a10b559
Revises: 837eddb8eee0
Create Date: 2019-12-09 08:15:42.068490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b986a10b559'
down_revision = '837eddb8eee0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collection_items', sa.Column('compressed_file', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('collection_items', 'compressed_file')
    # ### end Alembic commands ###
