"""empty message

Revision ID: a58cf42d5263
Revises: c7b452f40e8c
Create Date: 2020-02-20 18:02:06.061468

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a58cf42d5263'
down_revision = 'c7b452f40e8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tiles', sa.Column('max_x', sa.Float(), nullable=True))
    op.add_column('tiles', sa.Column('min_y', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tiles', 'min_y')
    op.drop_column('tiles', 'max_x')
    # ### end Alembic commands ###
