"""empty message

Revision ID: c7b452f40e8c
Revises: 4a2287967b77
Create Date: 2020-01-27 08:51:22.892688

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c7b452f40e8c'
down_revision = '4a2287967b77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collections', sa.Column('license', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('collections', 'license')
    # ### end Alembic commands ###
