"""empty message

Revision ID: de5df82f47a6
Revises: 94aac6fd8b37
Create Date: 2019-12-05 11:34:08.542958

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'de5df82f47a6'
down_revision = '94aac6fd8b37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assets', 'chunk_size_t',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               type_=sa.Float(precision=50),
               existing_nullable=True)
    op.alter_column('assets', 'chunk_size_x',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               type_=sa.Float(precision=50),
               existing_nullable=True)
    op.alter_column('assets', 'chunk_size_y',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               type_=sa.Float(precision=50),
               existing_nullable=True)
    op.alter_column('assets', 'raster_size_t',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               type_=sa.Float(precision=50),
               existing_nullable=True)
    op.alter_column('assets', 'raster_size_x',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               type_=sa.Float(precision=50),
               existing_nullable=True)
    op.alter_column('assets', 'raster_size_y',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               type_=sa.Float(precision=50),
               existing_nullable=True)
    op.alter_column('bands', 'resolution_x',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               type_=sa.Float(precision=50),
               existing_nullable=False)
    op.alter_column('bands', 'resolution_y',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               type_=sa.Float(precision=50),
               existing_nullable=False)
    op.alter_column('raster_size_schemas', 'chunk_size_t',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               type_=sa.Float(precision=50),
               existing_nullable=True)
    op.alter_column('raster_size_schemas', 'chunk_size_x',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               type_=sa.Float(precision=50),
               existing_nullable=False)
    op.alter_column('raster_size_schemas', 'chunk_size_y',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               type_=sa.Float(precision=50),
               existing_nullable=False)
    op.alter_column('raster_size_schemas', 'raster_size_t',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               type_=sa.Float(precision=50),
               existing_nullable=True)
    op.alter_column('raster_size_schemas', 'raster_size_x',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               type_=sa.Float(precision=50),
               existing_nullable=False)
    op.alter_column('raster_size_schemas', 'raster_size_y',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               type_=sa.Float(precision=50),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('raster_size_schemas', 'raster_size_y',
               existing_type=sa.Float(precision=50),
               type_=postgresql.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('raster_size_schemas', 'raster_size_x',
               existing_type=sa.Float(precision=50),
               type_=postgresql.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('raster_size_schemas', 'raster_size_t',
               existing_type=sa.Float(precision=50),
               type_=postgresql.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('raster_size_schemas', 'chunk_size_y',
               existing_type=sa.Float(precision=50),
               type_=postgresql.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('raster_size_schemas', 'chunk_size_x',
               existing_type=sa.Float(precision=50),
               type_=postgresql.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('raster_size_schemas', 'chunk_size_t',
               existing_type=sa.Float(precision=50),
               type_=postgresql.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('bands', 'resolution_y',
               existing_type=sa.Float(precision=50),
               type_=postgresql.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('bands', 'resolution_x',
               existing_type=sa.Float(precision=50),
               type_=postgresql.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('assets', 'raster_size_y',
               existing_type=sa.Float(precision=50),
               type_=postgresql.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('assets', 'raster_size_x',
               existing_type=sa.Float(precision=50),
               type_=postgresql.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('assets', 'raster_size_t',
               existing_type=sa.Float(precision=50),
               type_=postgresql.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('assets', 'chunk_size_y',
               existing_type=sa.Float(precision=50),
               type_=postgresql.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('assets', 'chunk_size_x',
               existing_type=sa.Float(precision=50),
               type_=postgresql.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('assets', 'chunk_size_t',
               existing_type=sa.Float(precision=50),
               type_=postgresql.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    # ### end Alembic commands ###
